#!/usr/bin/env python3
"""VM-only demo fixtures. No application processes or backups required.
Reuses service schema.sql files; inserts missing fixtures without deleting data.
Run: sudo python3 docker/postgres/seed-demo-data.py [--verify-only]
"""
import argparse
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]
DATABASES = {
    'order-service': 'order-srv-db', 'payment-service': 'payment-srv-db',
    **{name: name + '-db' for name in ('customer-service', 'product-aggregator-service',
       'product-discount-service', 'rating-service', 'inventory-service', 'notification-service')},
}
PROFILES = [('demo', 'customer1', 'Books,Electronics'), ('demo', 'customer2', 'Fitness,Home'),
            ('demo', 'admin1', 'Electronics'), ('other', 'othercustomer', 'Groceries')]
# Completed historical fixtures: no queued checkout jobs or Kafka events to replay.
ORDERS = [
    ('aws-demo-books-v1', 'customer1', 'BOOK-1', 'Everyday cooking', 'Books', 2, '22.00', '22.00'),
    ('aws-demo-fitness-v1', 'customer2', 'FIT-1', 'Training mat', 'Fitness', 1, '35.00', '29.75'),
    ('aws-demo-audio-v1', 'customer1', 'ELEC-1', 'Wireless headphones', 'Electronics', 1, '79.00', '67.15'),
]
# These two entity tables are normally created by Hibernate before schema.sql.
ENTITY_DDL = {
    'order-service': """CREATE TABLE IF NOT EXISTS orders (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id varchar(255),
      tenant varchar(255), amount numeric(38,2), status varchar(255)
      CHECK(status IN ('PENDING','CONFIRMED','FAILED','SHIPPED','DELIVERED')),
      created_at timestamp(6) with time zone);""",
    'payment-service': """CREATE TABLE IF NOT EXISTS payment (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id bigint,
      amount numeric(38,2), status varchar(255) CHECK(status IN ('SUCCESS','FAILED')),
      created_at timestamp(6) with time zone);""",
}
REGISTRY = 'CREATE TABLE IF NOT EXISTS aws_dev_seed (seed_key text PRIMARY KEY, entity_id bigint NOT NULL);'


def literal(value):
    return "'" + str(value).replace("'", "''") + "'"


def sql(service, statement):
    result = subprocess.run(['docker', 'exec', '-i', 'postgres', 'psql', '-X', '-qAt',
        '-v', 'ON_ERROR_STOP=1', '-U', 'postgres', '-d', DATABASES[service]],
        input=statement, text=True, capture_output=True, check=False)
    if result.returncode:
        raise RuntimeError(f'{service}: {result.stderr.strip()}')
    return result.stdout.strip()


def transaction(service, statement):
    # Same lock for each database makes retries/concurrent seed invocations safe.
    return sql(service, 'BEGIN; DO $$ BEGIN PERFORM pg_advisory_xact_lock(918002); END $$;\n'
               + statement + '\nCOMMIT;')


def require(service, expression, label):
    if sql(service, 'SELECT (' + expression + ');') != 't':
        raise RuntimeError('Verification failed: ' + label)


def initialize():
    # Preflight every schema before mutating any database.
    schemas = {s: (ROOT / s / 'src/main/resources/schema.sql').read_text() for s in DATABASES}
    for service, schema in schemas.items():
        transaction(service, ENTITY_DDL.get(service, '') + '\n' + schema + '\n' + REGISTRY)
        print(service + ': schema and catalog seeds ready', flush=True)
    for tenant, username, preferences in PROFILES:
        transaction('customer-service', f"""INSERT INTO customer_profile
          (tenant,username,email,phone,dob,preferences) VALUES
          ({literal(tenant)},{literal(username)},{literal(username+'@example.test')},
           '+1-202-555-0100','1995-06-15',{literal(preferences)}) ON CONFLICT DO NOTHING;""")
    for key, username, sku, name, category, qty, original, price in ORDERS:
        # Let PostgreSQL allocate IDs; never reserve IDs that could collide with real orders.
        transaction('order-service', f"""
        DO $$ DECLARE oid bigint; BEGIN
          IF NOT EXISTS (SELECT 1 FROM aws_dev_seed WHERE seed_key={literal(key)}) THEN
            INSERT INTO orders(customer_id,tenant,amount,status,created_at)
              VALUES ({literal(username)},'demo',{qty}*{price},'DELIVERED',now()-interval '2 days')
              RETURNING id INTO oid;
            INSERT INTO aws_dev_seed VALUES ({literal(key)},oid);
            INSERT INTO checkout(order_id,tenant,customer_id,idempotency_key,request_hash,state,address,tracking)
              VALUES(oid,'demo',{literal(username)},{literal(key)},'historical-demo-fixture',
              'DELIVERED','123 Example Street, Demo City','ECOM-'||oid);
            INSERT INTO order_item(order_id,sku,name,category,quantity,original_price,unit_price,subtotal)
              VALUES(oid,{literal(sku)},{literal(name)},{literal(category)},{qty},{original},{price},{qty}*{price});
          END IF;
        END $$;""")
        oid = int(sql('order-service', f'SELECT entity_id FROM aws_dev_seed WHERE seed_key={literal(key)};'))
        transaction('payment-service', f"""
        DO $$ DECLARE pid bigint; BEGIN
          IF NOT EXISTS (SELECT 1 FROM aws_dev_seed WHERE seed_key={literal(key)}) THEN
            INSERT INTO payment(order_id,amount,status,created_at)
              VALUES({oid},{qty}*{price},'SUCCESS',now()-interval '2 days') RETURNING id INTO pid;
            INSERT INTO aws_dev_seed VALUES({literal(key)},pid);
          END IF;
        END $$;""")
        items = json.dumps([{'sku': sku, 'quantity': qty}], separators=(',', ':'))
        transaction('inventory-service', f"""
        DO $$ BEGIN
          IF NOT EXISTS (SELECT 1 FROM aws_dev_seed WHERE seed_key={literal(key)}) THEN
            INSERT INTO reservation(tenant,order_id,state,items)
              VALUES('demo',{oid},'COMMITTED',{literal(items)});
            UPDATE stock SET available=available-{qty} WHERE sku={literal(sku)};
            IF NOT FOUND THEN RAISE EXCEPTION 'Missing stock for demo product'; END IF;
            INSERT INTO aws_dev_seed VALUES({literal(key)},{oid});
          END IF;
        END $$;""")
        # Match the application's deduplication keys, but do not publish fake Kafka traffic.
        transaction('customer-service', f"""
        WITH inserted AS (INSERT INTO consumed_order VALUES({literal(str(oid)+':CONFIRMED')})
          ON CONFLICT DO NOTHING RETURNING event_id)
        INSERT INTO category_history(tenant,username,category,purchases)
          SELECT 'demo',{literal(username)},{literal(category)},{qty} FROM inserted
          ON CONFLICT(tenant,username,category) DO UPDATE
          SET purchases=category_history.purchases+excluded.purchases;""")
        transaction('notification-service', f"""INSERT INTO notification_inbox
          (event_id,tenant,customer_id,order_id,status,created_at)
          VALUES({literal(str(oid)+':DELIVERED')},'demo',{literal(username)},{oid},'DELIVERED',
          now()-interval '2 days') ON CONFLICT DO NOTHING;""")
        print(f'Demo order #{oid}: {username}, {qty} x {sku}, delivered', flush=True)


def verify():
    for tenant, username, _ in PROFILES:
        require('customer-service', f"EXISTS(SELECT 1 FROM customer_profile WHERE tenant={literal(tenant)} "
                f"AND username={literal(username)} AND email<>'' AND phone<>'' AND dob IS NOT NULL)", username+' profile')
    for service, table, minimum in [('product-aggregator-service','product',10),
            ('product-discount-service','product_discount',5), ('rating-service','product_rating',6),
            ('inventory-service','stock',10)]:
        require(service, f'(SELECT count(*) FROM {table}) >= {minimum}', table)
        print(f'Verified {table}: at least {minimum} rows', flush=True)
    for key, username, sku, _, category, qty, _, price in ORDERS:
        value = sql('order-service', f'SELECT entity_id FROM aws_dev_seed WHERE seed_key={literal(key)};')
        if not value:
            raise RuntimeError('Missing demo order: '+key)
        oid = int(value)
        require('order-service', f"""EXISTS(SELECT 1 FROM orders o JOIN checkout c ON c.order_id=o.id
          WHERE o.id={oid} AND o.customer_id={literal(username)} AND o.tenant='demo'
          AND o.amount={qty}*{price} AND o.status=c.state
          AND o.amount=(SELECT sum(subtotal) FROM order_item WHERE order_id=o.id)
          AND (SELECT count(*) FROM order_item WHERE order_id=o.id)=1)
          AND EXISTS(SELECT 1 FROM order_item WHERE order_id={oid} AND sku={literal(sku)} AND quantity={qty})""",key+' order/items')
        require('payment-service', f"""EXISTS(SELECT 1 FROM payment p JOIN aws_dev_seed s ON s.entity_id=p.id
          WHERE s.seed_key={literal(key)} AND p.order_id={oid} AND p.amount={qty}*{price} AND p.status='SUCCESS')""",key+' payment')
        require('inventory-service', f"""EXISTS(SELECT 1 FROM reservation WHERE tenant='demo' AND order_id={oid}
          AND state='COMMITTED' AND items::jsonb @> '[{{"sku":"{sku}","quantity":{qty}}}]'::jsonb)
          AND EXISTS(SELECT 1 FROM stock WHERE sku={literal(sku)} AND available>=0)""",key+' inventory')
        require('customer-service', f"""EXISTS(SELECT 1 FROM category_history WHERE tenant='demo'
          AND username={literal(username)} AND category={literal(category)} AND purchases>={qty})
          AND EXISTS(SELECT 1 FROM consumed_order WHERE event_id={literal(str(oid)+':CONFIRMED')})""",key+' history')
        require('notification-service', f"""EXISTS(SELECT 1 FROM notification_inbox WHERE
          event_id={literal(str(oid)+':DELIVERED')} AND order_id={oid}
          AND tenant='demo' AND customer_id={literal(username)} AND status='DELIVERED')""",key+' notification')
        print(f'Verified demo order #{oid}: items, payment, inventory, customer history and notification', flush=True)
    print('Verified 4 customer profiles and 3 complete sample orders across all 8 application databases.', flush=True)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--verify-only', action='store_true')
    args = parser.parse_args()
    if not args.verify_only:
        initialize()
    verify()
