spring:
  application:
    name: product-aggregator-service
  profiles:
    active: local
  sql:
    init:
      mode: always
  kafka:
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 9104
management:
  endpoint:
    health:
      probes:
        enabled: true
