apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:stage1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9103
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://host.minikube.internal:4318
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.namespace=ecommerce,deployment.environment.name=stage
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1.0"
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9103
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9103
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: 9103
      targetPort: 9103
