# Learning credentials only. Jenkins should inject real environment credentials.
apiVersion: v1
kind: Secret
metadata:
  name: service-client-credentials
  namespace: ecommerce
type: Opaque
stringData:
  order-service: "LBOkQHGD24s1Wg7L7Bl4iul03PWxgZ0p7oNR-LMmIQ4"
  payment-service: "DN_T6e4herop-EqSOWtVB85PNY1UEddm9MofHQzP_r0"
