services:
  order:
    url: http://localhost:9101
  payment:
    url: http://localhost:9102
  notification:
    url: http://localhost:9103
  product:
    url: http://localhost:9104
  inventory:
    url: http://localhost:9105

security:
  jwt:
    jwk-set-uri: http://localhost:8180/realms/ecommerce/protocol/openid-connect/certs
